import Head from "next/head";
export const metadata = {
  title: "server fetch | Del-Next App",
  description: "Generated by DEL",
};
const productList = async() => {
    const res = await fetch("https://dummyjson.com/products");
    const result = await res.json()
    return result.products
    
}

const page = async () => {
    let products = await productList()
    return (
      <div>
        <Head>
          <title>Server Fetch | Practice NEXT.JS</title>
        </Head>

        {products.map((product) => (
          <h1 className=" ml-10" key={product.id}>
            products name : {product.title}
          </h1>
        ))}
      </div>
    );
};

export default page;