"use client";
import Head from "next/head";
import { useEffect, useState } from "react";

export const metadata = {
  title: "Client Fetch | Del-Next App",
  description: "Generated by DEL",
};

const ClientFetch = () => {
const [products, setProducts] = useState([])
useEffect(() => {
  fetch("https://dummyjson.com/products")
    .then((response) => response.json())
    .then((data) => setProducts(data.products));
    }, [])

return (
  <div>
    <Head>
      <title>Client Fetch | Practice NEXT.JS</title>
    </Head>
    {products.map((product) => (
      <h1 className=" ml-10" key={product.id}>
        products name : {product.title}
      </h1>
    ))}
  </div>
);
};

export default ClientFetch;
