import React from 'react';
export const metadata = {
  title: "static server fetch | Del-Next App",
  description: "Generated by DEL",
};
const page = () => {
  return (
    <div className='text-center mt-4'>
      <h1 className='text-4xl mb-10'>static server fetch</h1>
      <h5>getStaticProps not work on - NEXT JS 13.4</h5>
    </div>
  );
};

export default page;